from enum import Enum


class TransferType(str, Enum):
    IMPS = "IMPS"
    NEFT = "NEFT"
    RTGS = "RTGS"
    UPI = "UPI"


class TransactionStatus(str, Enum):
    INITIATED = "INITIATED"
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"
    REVERSED = "REVERSED"


class EventType(str, Enum):
    PAYOUT_INITIATED = "PAYOUT_INITIATED"
    PAYOUT_ACCEPTED = "PAYOUT_ACCEPTED"
    PROVIDER_PROCESSING = "PROVIDER_PROCESSING"
    PAYOUT_STATUS_CALLBACK = "PAYOUT_STATUS_CALLBACK"
    STATUS_CHECK = "STATUS_CHECK"
    LEDGER_DEBIT = "LEDGER_DEBIT"
    LEDGER_REVERSAL = "LEDGER_REVERSAL"
    LEDGER_CREDIT = "LEDGER_CREDIT"


class EventSource(str, Enum):
    API_CLIENT = "API_CLIENT"
    DECENTRO_GATEWAY = "DECENTRO_GATEWAY"
    BANK_PARTNER_GATEWAY = "BANK_PARTNER_GATEWAY"
    BANK_PARTNER_CALLBACK = "BANK_PARTNER_CALLBACK"
    DECENTRO_STATUS_POLLER = "DECENTRO_STATUS_POLLER"
    DECENTRO_LEDGER = "DECENTRO_LEDGER"


class LedgerEntryType(str, Enum):
    DEBIT = "DEBIT"
    REVERSAL = "REVERSAL"
    CREDIT = "CREDIT"


class FailureStage(str, Enum):
    CLIENT_REQUEST = "CLIENT_REQUEST"
    AUTHENTICATION_AUTHORIZATION = "AUTHENTICATION_AUTHORIZATION"
    DECENTRO_GATEWAY = "DECENTRO_GATEWAY"
    PROVIDER_ROUTING = "PROVIDER_ROUTING"
    BENEFICIARY_SWITCH = "BENEFICIARY_SWITCH"
    BENEFICIARY_BANK = "BENEFICIARY_BANK"
    LEDGER_EXECUTION = "LEDGER_EXECUTION"
    UNKNOWN = "UNKNOWN"
